global:
  scrape_interval: 15s
  evaluation_interval: 15s          

  external_labels:
    env: local                      

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: alertmanager
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: backend
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['backend:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: backend
