groups:
  - name: wearipedia.rules
    rules:
      # ingestion job threw errors in the last minute
      - alert: IngestionJobFailed
        expr: rate(ingestion_errors_total[1m]) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Ingestion errors detected"
          description: |
            {{ $value | humanize }} errors/sec seen in the ingestion pipeline
            over the last minute.

      #90th percentile API latency is > 2 s for 5 min
      - alert: HighAPI90pLatency
        expr: histogram_quantile(0.90,
                rate(request_latency_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "API latency is high"
          description: |
            90-th percentile latency has been above 2 s for 5 min.
              
      - alert: TestAlwaysFires
        expr: vector(1)
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Test alert: always true"

