services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       wearables
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  ingestor:
    build: ./ingest
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST:      db
      PGPORT:      5432
      PGUSER:      postgres
      PGPASSWORD:  postgres
      PGDATABASE:  wearables
      DATA_DIR:    /data             
    volumes:
      - ../task_0b/data/participant_001:/data:ro
      - ingest-state:/checkpoint      
    restart: on-failure

volumes:
  db-data:
  ingest-state:
