version: "3.9"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wearables
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: wearables
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    ports: ["8000:8000"]

  frontend:
    build: ./frontend
    depends_on: [backend]
    ports: ["3000:80"]
  
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"       # SMTP
      - "8025:8025"       # Web UI

volumes:
  db-data:
    external: true
    name: task_1_ingestion_db-data  # task 1 volume

